# Generated by Django 3.2.5 on 2021-08-15 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Info',
            fields=[
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('phoneNo', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('furnitureId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('furnitureName', models.CharField(max_length=50)),
                ('furnitureImg', models.ImageField(upload_to='images/')),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('orderDate', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('furnitureId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.furniture')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('furnitureId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.furniture')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewCount', models.IntegerField()),
                ('furnitureId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.furniture')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('userId', 'furnitureId')},
            },
        ),
    ]
