# Generated by Django 3.2.5 on 2021-08-24 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20210824_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='city',
        ),
        migrations.AlterField(
            model_name='order',
            name='shippingAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='ecommerce.customer_addresses'),
        ),
    ]
