# Generated by Django 3.2.5 on 2021-08-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_category_categoryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='furnitureImg',
            field=models.ImageField(upload_to=None),
        ),
    ]
