# Generated by Django 3.2.5 on 2021-08-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_alter_furniture_furnitureimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='furnitureDesc',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='furniture',
            name='furnitureImg',
            field=models.ImageField(upload_to='furniture'),
        ),
    ]
