# Generated by Django 3.2.5 on 2021-08-17 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ecommerce', '0006_auto_20210816_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('addressId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('postcode', models.IntegerField(max_length=8)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cart_Products',
            fields=[
                ('cartId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('dateCreated', models.DateField(auto_now=True)),
                ('furnitureId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.furniture')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('phoneNo', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('dob', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Addresses',
            fields=[
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('addressId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.addresses')),
            ],
            options={
                'unique_together': {('userId', 'addressId')},
            },
        ),
        migrations.CreateModel(
            name='Order_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furnitureId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.furniture')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer_info',
            name='customerId',
        ),
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='furnitureId',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Customer_Info',
        ),
        migrations.AddField(
            model_name='order_products',
            name='orderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.customer'),
        ),
        migrations.AlterUniqueTogether(
            name='order_products',
            unique_together={('orderId', 'furnitureId')},
        ),
    ]
