# Generated by Django 3.2.5 on 2021-08-27 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_furniture_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniture',
            name='slug',
        ),
    ]
