# Generated by Django 3.2.5 on 2021-08-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_auto_20210817_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='postcode',
            field=models.IntegerField(),
        ),
    ]
