# Generated by Django 3.2.5 on 2021-08-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_remove_furniture_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='slug',
            field=models.SlugField(default='furnitureid', max_length=100),
            preserve_default=False,
        ),
    ]
