# Generated by Django 3.2.5 on 2021-08-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_furniture_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_products',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
