# Generated by Django 3.2.5 on 2021-08-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_alter_order_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='soldOut',
            field=models.BooleanField(default=0),
        ),
    ]
