# Generated by Django 3.2.5 on 2021-08-28 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0010_auto_20210828_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_products',
            name='furnitureId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.furniture'),
        ),
        migrations.AlterField(
            model_name='cart_products',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
