# Generated by Django 3.2.5 on 2021-08-17 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_furniture_soldout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='isCompleted',
        ),
    ]
