# Generated by Django 3.2.5 on 2021-08-17 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_rename_status_order_iscompleted'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order_products',
            unique_together=set(),
        ),
    ]
