# Generated by Django 3.2.5 on 2021-08-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_auto_20210828_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_products',
            name='slug',
            field=models.SlugField(default='furnitureId'),
            preserve_default=False,
        ),
    ]
