# Generated by Django 3.2.5 on 2021-08-18 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_auto_20210818_1648'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order_products',
            unique_together=set(),
        ),
    ]
