# Generated by Django 3.2.5 on 2021-09-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_auto_20210901_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='unitPrice',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
