# Generated by Django 3.2.5 on 2021-09-01 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0016_auto_20210901_1241'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer_addresses',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='customer_addresses',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='customer_profile',
            name='id',
        ),
        migrations.AddField(
            model_name='customer_profile',
            name='address1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer_profile',
            name='address2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer_profile',
            name='postcode',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='customer_profile',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer_profile',
            name='town',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer_profile',
            name='custId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Addresses',
        ),
        migrations.DeleteModel(
            name='Customer_Addresses',
        ),
    ]
