# Generated by Django 3.2.5 on 2021-09-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_auto_20210901_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_products',
            name='slug',
        ),
        migrations.AddField(
            model_name='cart_products',
            name='fidSlug',
            field=models.SlugField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cart_products',
            name='uidSlug',
            field=models.SlugField(max_length=10, null=True),
        ),
    ]
