# Generated by Django 3.2.5 on 2021-09-02 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_auto_20210902_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_products',
            old_name='fidSlug',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='cart_products',
            name='uidSlug',
        ),
    ]
