# Generated by Django 3.2.5 on 2021-09-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_auto_20210906_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='yearPurchased',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
