# Generated by Django 3.2.5 on 2021-09-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0024_alter_donation_donationimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donationImg',
        ),
        migrations.AddField(
            model_name='donation',
            name='image',
            field=models.ImageField(null=True, upload_to='donate'),
        ),
    ]
