# Generated by Django 3.2.5 on 2021-09-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0026_alter_donation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='image',
            field=models.ImageField(upload_to='donation'),
        ),
    ]
