# Generated by Django 3.2.5 on 2021-09-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0031_auto_20210914_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='isApproved',
            field=models.BooleanField(null=True),
        ),
    ]
