# Generated by Django 3.2.5 on 2021-09-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0032_alter_donation_isapproved'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='slug',
            field=models.SlugField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
