# Generated by Django 3.2.5 on 2021-09-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0034_remove_donation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='slug',
            field=models.SlugField(default='donationId', max_length=100),
            preserve_default=False,
        ),
    ]
