# Generated by Django 4.2.1 on 2023-08-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0036_auto_20210918_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='yearPurchased',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
